"""empty message

Revision ID: 35d0780edb35
Revises: 2819548b55db
Create Date: 2022-08-13 18:11:31.788890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d0780edb35'
down_revision = '2819548b55db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('venues', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('venues', 'facebook_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('venues_website_key', 'venues', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venues_website_key', 'venues', ['website'])
    op.alter_column('venues', 'facebook_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('venues', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('artists', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
